### ISSUE TITLE
unable to reset password

### ISSUE THREAD

**Issue by eleedom** [Mermaid-Chart/issue-tracker#77]
**Describe the bug**
i am unable to reset my password

**To Reproduce**
attempt to sign in 
credentials invalid
click reset password
receive reset password email, follow link
enter new password, click submit, submit button greys out but stay on page
attempt login again with new passwork credentials invalid

**Expected behavior**
password to be reset

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: mac
 - OS: 14.4.1
 - Browser Chrome
 - Version 126.0.6478.127

**Additional context**

**Comment by stempy** [comment]
I have the same issue here.  

1. try to login, invalid credentials
2. try to reset password, get email link, click link, open reset page
3. enter new password and does not do anything when clicking

OS: Win 11
Browser: Brave (tried with sheilds on and off)

**Comment by huynhicode** [comment]
@eleedom @stempy Thanks for reporting!

We have released a fix for the password reset issue. Would you mind checking to see if you are able to reset your password?

**Comment by eleedom** [comment]
yeah that looks better.  was able to reset password and login.

thanks for the quick response

**Comment by stempy** [comment]
> @eleedom @stempy Thanks for reporting!
> 
> We have released a fix for the password reset issue. Would you mind checking to see if you are able to reset your password?

@huynhicode Yep, password reset works well now. Thanks for that.

**Comment by magic-madrigal** [comment]
I'm trying to log in, but it says I have the wrong password. I reset it, and it accepted it, but it still doesn't let me log in.
