### ISSUE TITLE
Editor syncs chart unnecessarily after panning on large charts

### ISSUE THREAD

**Issue by IanDonn95** [Mermaid-Chart/issue-tracker#90]
**Describe the bug**
Whenever the chart window is panned (right-click and drag without adjusting any nodes or connections), the editor pops up a modal saying "The diagram is out of sync. It will be updated automatically". However, as now changes have been made, the sync is not necessary and is just an annoying popup.

**To Reproduce**
1. Create a new mermaid chart
2. Remove all the default "tutorial" nodes
3. Add around 80 nodes connected one after the other in a chain (sufficient complexity to reliably trigger the modal after each scroll for me)
4. Pan the editor
5. See the Syncing modal appear on screen for about a second

**Expected behavior**
Panning should not cause the sync modal to appear or even have any need to check for updates at all. When panning a small chart, no Sync modal message appears.

**Screenshots**
![image](https://github.com/user-attachments/assets/82f694fc-80b7-4c7a-88bf-b54700697212)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome v128.0.6613.85
 - Version: not sure, whatever was live at `https://www.mermaidchart.com/app/projects/<project-id>/diagrams/<diagram-id>/version/<diagram-version?>/edit` on 9/3/24. Update- the version live on 12/18/24 (v2.29.16) performed better but can still be coaxed to show the behavior with a larger chart.
 - 
**Additional context**
I experience this consistently on my main diagram with ~150 nodes and even more connections than that.

**Comment by akshatha1710** [comment]
@IanDonn95 
When we tested it with the latest release version (v2.29.16) , we're not able to reproduce this issue. Can you please verify that this issue is fixed on your side?

**Comment by IanDonn95** [comment]
@akshatha-mermaidchart thanks for looking into this! I can see my example case no longer pans, but my very large chart that I actually used, which I originally discovered this behavior on, still presents the "out of sync" message after panning.
Modifying my demo example, I can reliably get the message again if I increase the number of nodes to 80 and link each node to the next one. I'll update the reproduction steps with these more intense requirements.
![synthetic-example](https://github.com/user-attachments/assets/e4031fa1-57df-4f9b-af03-7fa724fe8086)
Here is a screenshot of my actual chart if you want to get an idea of the complexity I am trying to work with. I'm happy to provide the flowchart data if you want to work directly with this case; none of it is private data I need to keep secret.
![real-world-example](https://github.com/user-attachments/assets/e7fa3aa7-9141-4018-835a-6d547f5f2398)

**Comment by cybersteve547** [comment]
Hm, i have a similar issue however for me it happens after ~10 shapes and dosent need panning
check the newest issues for it.
